- hosts: localhost
  connection: local
  roles:
    - { role: avinetworks.ansible-role-avicontroller-vmware }
  vars:
    vc_host: labvc01
    vc_user: administrator@vsphere.local
    vc_password: password
    ova_path:  ./controller-17.2.11-9014.ova
    vc_dc: lab
    vc_cluster: zoo
    vc_folder: avi
    node1_vm_name: avi01a-1
    node1_ip: 192.168.1.11
    node2_vm_name: avi01a-2
    node2_ip: 192.168.1.12
    node3_vm_name: avi01a-3
    node3_ip: 192.168.1.13
    node_mgmt_pg: "VM Network"
    node_mgmt_netmask: 255.255.248.0
    node_mgmt_gateway: 192.168.0.1
    node_number_of_cpus: 8
    node_memory: "24576"
    node_disk_size: "128"
    node_disk_mode: "thin"
    node_datastore: minas-LUN-1
    node_power_on: true

  tasks:
    - name: Deploy Avi Controllers
      deploy_controller:
        ovftool_path: /usr/lib/vmware-ovftool
        vcenter_host: "{{ vc_host }}"
        vcenter_user: "{{ vc_user }}"
        vcenter_password: "{{ vc_password }}"
        con_ova_path: "{{ ova_path }}""
        con_datacenter: "{{ vc_dc }}"
        con_cluster: "{{ vc_cluster }}"
        con_vm_name: "{{ item.node_vm_name }}"
        con_vcenter_folder: "{{ vc_folder }}"
        con_mgmt_network: "{{ node_mgmt_pg }}"
        con_mgmt_ip: "{{ item.node_mgmt_ip }}"
        con_mgmt_mask: "{{ node_mgmt_mask }}"
        con_default_gateway: "{{ node_mgmt_gateway }}"
        con_number_of_cpus: "{{ node_number_of_cpus }}"
        con_memory: "{{ node_memory }}"
        con_disk_size: "{{ node_disk_size }}"
        con_disk_mode: "{{ node_disk_mode }}"
        con_datastore: "{{ node_datastore }}"
        con_power_on: "{{ node_power_on }}"
      with_items:
        - { node_vm_name: "{{ node1_vm_name }}", node_mgmt_ip: "{{ node1_ip }}" }
        - { node_vm_name: "{{ node2_vm_name }}", node_mgmt_ip: "{{ node2_ip }}" }
        - { node_vm_name: "{{ node3_vm_name }}", node_mgmt_ip: "{{ node3_ip }}" }
