- hosts: localhost
  connection: local
  vars:
    avi_controller: 192.168.1.11
    avi_username: admin
    api_version: 17.2.7
    avi_password: AviNetworks123!
    vc_host: labvc01
    vc_user: administrator@vsphere.local
    vc_password: VMware1!
    vc_dc: lab
    vc_cluster: zoo
    vc_folder: avi
    vmware_cloud_name: vmc
    vmware_mgmt_pg: "VM Network"
    discovery_time: 120
    service_engine_group_name: seg01d
    service_engine_group_prefix_name: seg01d
    net_name: "VM Network"
    net_address: 192.168.0.0
    net_prefix: 21
    beg_addr: 192.168.1.100
    end_addr: 192.168.1.109

  roles:
    - { role: avinetworks.avisdk }

  tasks:
    - name: Defining cloud configuration
      set_fact:
        avi_config:
          avi_cloud_discovery_wait: "{{ discovery_time }}"
          cloud:
            - name: "{{ vmware_cloud_name }}"
              vtype: CLOUD_VCENTER
              dhcp_enabled: true
              license_type: "LIC_CORES"
              vcenter_configuration:
                username: "{{ vc_user }}"
                password: "{{ vc_password }}"
                datacenter: "{{ vc_dc }}"
                management_network: "/api/vimgrnwruntime/?name={{ vmware_mgmt_pg }}"
                privilege: "WRITE_ACCESS"
                vcenter_url: "{{ vc_host }}"

          serviceenginegroup:
            - name: "{{ service_engine_group_name }}"
              cloud_ref: "/api/cloud/?name={{ vmware_cloud_name }}"
              vcenter_folder: "{{ vc_folder }}"
              vcenter_clusters:
                cluster_refs:
                  - "/api/vimgrclusterruntime/?name={{ vc_cluster }}"
                include: True
              max_se: 4
              buffer_se: 0
              se_name_prefix: "{{ service_engine_group_prefix_name }}"
#          network:
#            - name: "{{ net_name }}"
#              tenant_ref: "/api/tenant/?name=admin"
#              cloud_ref: "/api/cloud/?name={{ vmware_cloud_name }}"
#              configured_subnets:
#              - prefix:
#                  ip_addr:
#                    type: V4
#                    addr: "{{ net_address }}"
#                  mask: "{{ net_prefix }}"
#                static_ranges:
#                - begin:
#                    type: V4
#                    addr: "{{ beg_addr }}"
#                  end:
#                    type: V4
#                    addr: "{{ end_addr }}"
#              exclude_discovered_subnets: false
#              vimgrnw_ref: "/api/vimgrnwruntime/?name={{ net_name }}"
#              synced_from_se: false
#              dhcp_enabled: false
#              vcenter_dvs: true
    - name: Configuring the cloud
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_credentials:
          controller: "{{ avi_controller }}"
          username: "{{ avi_username }}"
          password: "{{ avi_password }}"
          api_version: "{{ api_version }}"
        avi_config: "{{ avi_config }}"
