---
- connection: local
  hosts: localhost
  roles:
  - avinetworks.avisdk
  tasks:
    - name: "Check if user {{ gslb_username }} exists on Avi"
      avi_api_session:
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        controller: "{{ avi_controller }}"
        api_version: "{{ api_version }}"
        http_method: get
        path: user
        params:
          name: "{{ gslb_username }}"
      register: user_exists
    - avi_api_session:
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        controller: "{{ avi_controller }}"
        api_version: "{{ api_version }}"
        http_method: post
        path: user
        data:
          name: "{{ gslb_username }}"
          username: "{{ gslb_username }}"
          password: "{{ gslb_password }}"
          access:
            - role_ref: "/api/role?name=System-Admin"
              tenant_ref: "/api/tenant?name=admin"
          user_profile_ref: "/api/useraccountprofile?name=No-Lockout-User-Account-Profile"
      name: "If user {{ gslb_username }} doesn't exist create it"
      when:
        user_exists.obj.count == 0
    - name: "Get cluster object using avi_api_session"
      avi_api_session:
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        controller: "{{ avi_controller }}"
        api_version: "{{ api_version }}"
        http_method: get
        path: cluster
      register: cluster_info
    - avi_gslb:
        avi_api_update_method: patch
        avi_api_patch_op: add
        api_context: '{{ api_context | default(omit) }}'
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        controller: "{{ avi_controller }}"
        api_version: "{{ api_version }}"
        sites:
        - enabled: true
          port: 443
          member_type: GSLB_ACTIVE_MEMBER
          cluster_uuid: "{{ cluster_info['obj'].uuid }}"
          ip_addresses:
          - type: V4
            addr: "{{ node1_avi_controller_mgmt_ip }}"
          - type: V4
            addr: "{{ node2_avi_controller_mgmt_ip }}"
          - type: V4
            addr: "{{ node3_avi_controller_mgmt_ip }}"
          name: "{{ gslb_site_name }}"
          username: "{{ gslb_username }}"
          password: "{{ gslb_password }}"
        send_interval: "{{ gslb_send_interval }}"
        name: "{{ gslb_cluster_name }}"
        leader_cluster_uuid: "{{ cluster_info['obj'].uuid }}"
      name: "Create GSLB cluster: {{ gslb_cluster_name }}"
